configuration: Debug
image: Visual Studio 2019

environment:
  app_version: '5.0.0'

version: '$(app_version).{build}'

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	

cache:
  packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
 - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
 - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
 - nuget sources add -name databinding -source https://ci.appveyor.com/nuget/ospsuite-databinding
 - nuget restore

build:
  publish_nuget: true
  verbosity: minimal

test:
  assemblies:
    - OSPSuite.DataBinding.DevExpress.Tests.dll

skip_commits:
  files:
    - '*.md'

pull_requests: 
  do_not_increment_build_number: true     

nuget: 
  disable_publish_on_pr: true  

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
  - master
  - develop